name: ${project.name}
main: net.daboross.bukkitdev.spawndistance.SpawnDistance
version: ${project.version}
author: Dabo Ross
description: Allows you to check your distance from the world's spawn
commands:
  spawndistance:
    description: Shows you your distance from the world's spawn
    usage: /<command>
    permission: spawndistance.use
    aliases: [sd]
